name: Run Tests
on:
  push:
    branches:
      - "**"
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "17"

      - name: Install dependencies
        run: yarn install

      - name: Run tests
        run: yarn test
